### PR TITLE
Initialize ExportData with tmp config obj from AggregatedData.

### PR DESCRIPTION
**Pull request by perolavsvendsen**
Solve #625 and silence warning about erroneous config. It is spamming the logs on our service, and the text is misleading (see issue).

### CODE REVIEW

**Comment by perolavsvendsen** [comment]
Ref options listed in the issue, I am _not_ convinced that this is the best way of solving this. It feels a bit like duct tape. Open for opinions and suggestions.

**Comment by tnatt** [comment]
yes, it feels a bit hacky which is why I took it away recently 🙂 but I see the problem with logs being spammed. This AggregatedData needs a bit of attention later, but for now I guess taking this fake config back could be an option..

Or probably better, rewrite: 
https://github.com/equinor/fmu-dataio/blob/bec764718c6dbc41a5b56cd640004cf4174deb45/src/fmu/dataio/dataio.py#L475

to:
` self._config_is_valid =  global_configuration.is_valid(self.config) if self.config else False`

That will silence the pydantic warnings, and there is no need of validating the config if it is not given anyway 👍

**Comment by perolavsvendsen** [comment]
> https://github.com/equinor/fmu-dataio/blob/bec764718c6dbc41a5b56cd640004cf4174deb45/src/fmu/dataio/dataio.py#L475
> 
> to: ` self._config_is_valid = global_configuration.is_valid(self.config) if self.config else False`
> 
> That will silence the pydantic warnings, and there is no need of validating the config if it is not given anyway 👍

Yes, that looks potentially more elegant. But are there unwanted side-effects? Wouldn't this fail to warn if `ExportData` is attempted initialized without config in other contexts? (Do we want that?)

**Comment by tnatt** [comment]
> > https://github.com/equinor/fmu-dataio/blob/bec764718c6dbc41a5b56cd640004cf4174deb45/src/fmu/dataio/dataio.py#L475
> > 
> > to: ` self._config_is_valid = global_configuration.is_valid(self.config) if self.config else False`
> > That will silence the pydantic warnings, and there is no need of validating the config if it is not given anyway 👍
> 
> Yes, that looks potentially more elegant. But are there unwanted side-effects? Wouldn't this fail to warn if `ExportData` is attempted initialized without config in other contexts? (Do we want that?)

Hm, maybe... And eventually we are moving towards requiring a valid config as input, so probably making the fake config here is the best solution for now 👍 and then we'll address it later when we give some attention to this class 🙂

**Review by tnatt — APPROVED** [review]

**Comment by perolavsvendsen** [comment]
Ah, did not see the last comment until now. Tried the (previously) suggested change. Can revert back if we liked the first one better. `#dontmerge`

**Comment by perolavsvendsen** [comment]
Which one do we want? First or second...?

**Comment by tnatt** [comment]
> Which one do we want? First or second...?

I say first!

**Comment by perolavsvendsen** [comment]
@tnatt happy? OK to merge...?

**Pull request merged**
