### PR TITLE
Schema restructure

### PR DESCRIPTION
**Pull request by perolavsvendsen**
This PR restructures the JSON Schema, in an attempt to make it more readable and to improve error messages. Relates to ongoing work on automated schema documentation.

Draft for now, for discussion.

### CODE REVIEW

**Review by daniel-sol — APPROVED** [review]
I have to admit that I don't have much to contribute with when it comes to this. But can't spot anything that screams wrong at me..

**Comment by perolavsvendsen** [comment]
Related to #348

**Comment by perolavsvendsen** [comment]
Might rather increment this to `0.9.0` instead of overwriting existing `0.8.0` and combine it with the ongoing work on schema documentation.

**Comment by perolavsvendsen** [comment]
- [ ] Put new structure in `0.9.0`, keep `0.8.0` as-is
- [ ] Expand tests to also cover `0.9.0`

**Comment by perolavsvendsen** [comment]
If merged, this _should_ create another schema labelled `0.9.0` in the structure and on the endpoint, while not affect any production of metadata or any existing validation (because outgoing metadata will still be hardcoded to validate against `0.8.0`).

**Review by equinor-ruaj — APPROVED** [review]
lgtm
Though my guess is as good as yours on whether anything will stop working 😅

**Comment by perolavsvendsen** [comment]
This PR is blocked by missing functionality in sumo uploader. We need to be able to test the schema in `dev` first. Functionality is to be added to the sumo uploader to facilitate this.

Meanwhile, there are changes to the 0.8.0 schema. So these changes must be retrofitted to this PR before merging.

**Comment by rwiker** [comment]
Addressed in https://github.com/equinor/sumo-core-nodejs/pull/270.

**Comment by perolavsvendsen** [comment]
Closing this in favor of ongoing work solving #423

**Pull request closed without merging**
