### PR TITLE
Correct forcefolder

### PR DESCRIPTION
**Pull request by jcrivenaes**

### CODE REVIEW

**Comment by perolavsvendsen** [comment]
What was the issue...? What is the updated behavior?

**Comment by jcrivenaes** [comment]
> What was the issue...? What is the updated behavior?

Just buggy; it came in the wrong place when running Drogon RMS interactive

**Comment by perolavsvendsen** [comment]
> > What was the issue...? What is the updated behavior?
> 
> Just buggy; it came in the wrong place when running Drogon RMS interactive

👍Did not read it through, but any needs to verify that behavior is as expected also in batch? Used actively by some users, e.g JS...

**Comment by jcrivenaes** [comment]
I think you are right @perolavsvendsen ; there are still issues here. I will open another PR (JS are still running the legacy version I think?)

**Pull request merged**
