### PR TITLE
FIX: Update schema due to new pydantic version

### PR DESCRIPTION
**Pull request by tnatt**
PR to fix our failing tests.
Pydantic has done a change to how they handle enum literals https://github.com/pydantic/pydantic/pull/8944
This causes changes to the schema.

### CODE REVIEW

**Comment by tnatt** [comment]
It was not as easy as just updating the schema.. they must have introduced other changes as well. I will fix :)

**Comment by tnatt** [comment]
OK, more tricky than expected... somehow the Enum objects are now being dumped as objects instead of values when dumping to dictionary. There exists an option `use_enum_values=True` to turn off this behaviour.. but for some reason I can't get it to work! And I know it worked before because I added it to the PR #599:
Could the change here https://github.com/pydantic/pydantic/pull/8920/files have impacted it? 
You will need to have a look with me on Mobnday @mferrera 🙂

**Comment by tnatt** [comment]
probably the same issue: https://github.com/pydantic/pydantic/issues/9235

**Comment by tnatt** [comment]
See pydantic issue #9235
https://github.com/pydantic/pydantic/issues/ 

probably related

**Comment by perolavsvendsen** [comment]
I don't fully understand this PR - only the (generated) schema has changed (?)

**Comment by mferrera** [comment]
The new Pydantic version has changed how it handles values that come from enums, which I guess their source (an enum) now being kept in the schema. This Pydantic version has a bug that isn't resolved yet, so it's possible that this may change again.

Not sure how these schema changes stand with respect to validating. I don't think we've checked yet since Pydantic hasn't fixed the issue yet (#600)

**Pull request closed without merging**
