### PR TITLE
allow field_region as content

### PR DESCRIPTION
**Pull request by perolavsvendsen**
Solving/contributing to #200 

This PR allows `field_region` as content. It is singular, and may be joined by `field_regions` in the future for objects containing many regions. This is request from REP and JS, purpose is to the able to effectively and consistently identify specific type of region from FMU results. The more generic `regions` is already allowed, but will include other types of regions as well.

### CODE REVIEW

**Review by jcrivenaes — COMMENTED** [review]
Should regions have a number attached also? I think so.

Also, since the example refers to Drogon, use e,g, `CentralHorst` as a name example. This is nuregion no. 6

**Comment by perolavsvendsen** [comment]
> Should regions have a number attached also? I think so.
> 
> Also, since the example refers to Drogon, use e,g, `CentralHorst` as a name example. This is nuregion no. 6

That is only valid if regions are numbered. If and when represented by a grid parameter, they will be associated with a code/number. But this is the polygon(s), they have no number.

**Comment by jcrivenaes** [comment]
> > Should regions have a number attached also? I think so.
> > Also, since the example refers to Drogon, use e,g, `CentralHorst` as a name example. This is nuregion no. 6
> 
> That is only valid if regions are numbered. If and when represented by a grid parameter, they will be associated with a code/number. But this is the polygon(s), they have no number.

Perhaps not, but the referall to region number is still important. We could have extended content as e.g. seismics:

`content = {"field_region": {"name": "CentralHorst", "number": 6} }`

where number is optional

**Comment by perolavsvendsen** [comment]
We can try to make number supported and optional. The extra name is redundant, as it is covered in `data.name`. But could possibly live with a duplicate - or there may be instances where two different is needed.

**Comment by perolavsvendsen** [comment]
`data.field_region` now required when `data.content` == "field_region", and subkey `data.field_region.id` is required.

This is under the assumption that most have a numeric ID for their field regions, and that those who have not can make one.
This is also under the assumption that the term "field region" is interpreted similarly across FMU. E.g. that each FMU workflow is able to single out one entity which is the "field region", and that this is the one visualized in REP.

This may break if some asset wants two different sets of polygons displayed, and refer to both as "field regions". Definition of "field region" assumed here is:

- Polygons that marks the boundaries between different geographical areas of a field.

**Comment by perolavsvendsen** [comment]
- [ ] Confirm that this works for Drogon
- [ ] Confirm that this works for Johan Sverdrup
- [ ] Confirm that this works for REP

**Review by jcrivenaes — APPROVED** [review]
I think we should try this :+1:

**Pull request merged**
