### PR TITLE
Schema docs

### PR DESCRIPTION
**Pull request by adnejacobsen**
- New FMU schema documentation website under `/schema/docs`
    - Exposed in a new `docs` component in the Radix-app
- Add CORS headers to fmu-schemas nginx config (allows us to fetch the schema from the browser)

To run locally:
-  install node + npm
- `cd schema/docs`
- `npm install`
- `npm run start`
-  open `localhost:3000` 

The website currently builds the documentation from a local copy of `fmu_results.json`. I would like to fetch the schema from the Radix app: `https://main-fmu-schemas-dev.radix.equinor.com/schemas/0.8.0/fmu_results.json` but I can't do that until the CORS headers have been added.

### CODE REVIEW

**Comment by perolavsvendsen** [comment]
#166

**Comment by perolavsvendsen** [comment]
Failing tests are due to #349

**Comment by perolavsvendsen** [comment]
Failing tests should be OK now given latest updates of `main`. Possibly `main` must be merged into this branch for them to pass.

**Comment by perolavsvendsen** [comment]
Is this based on the restructured schema (#346), or will they collide with each other?

**Comment by adnejacobsen** [comment]
> Is this based on the restructured schema (#346), or will they collide with each other?

It's based on the "old" 0.8.0 schema, but it supports some variations. It uses a local copy of the schema for now so should not be affected by changes in the schema. I suggest we push this and will make a new PR which builds the docs based on the "live" schema.

**Comment by perolavsvendsen** [comment]
Just to be clear, this creates the schema documentation in a separate app based on a local copy of the schema (for now)?

**Review by perolavsvendsen — APPROVED** [review]
Part of a bigger thing, but I think we should be good merging this as it should not affect any existing features.

**Comment by adnejacobsen** [comment]
> Just to be clear, this creates the schema documentation in a separate app based on a local copy of the schema (for now)?

Yes thats right 👍 Technically the same Radix app, but a separate component

**Pull request merged**
