### PR TITLE
ENH: Add facies_thickness as content type

### PR DESCRIPTION
**Pull request by janbjorge**
Resolves: https://github.com/equinor/fmu-dataio/issues/464

### CODE REVIEW

**Comment by perolavsvendsen** [comment]
That was a lot of added lines 🤯

- [ ] Also add `facies_thickness` to legacy schema, as we need it to have effect asap

**Comment by janbjorge** [comment]
> That was a lot of added lines 🤯
> 
>     * [ ]  Also add `facies_thickness` to legacy schema, as we need it to have effect asap

Yeah, at some point we need to look at how the schema is generated. Im sure their are options that identical objects reused insted of recreated.

**Comment by perolavsvendsen** [comment]
> > That was a lot of added lines 🤯
> > ```
> > * [ ]  Also add `facies_thickness` to legacy schema, as we need it to have effect asap
> > ```
> 
> Yeah, at some point we need to look at how the schema is generated. Im sure their are options that identical objects reused insted of recreated.

In the legacy schema, adding `facies_thickness` would simply be adding one more entry to that one list. However, now each allowed content lives much further down in the hierarchy. So there are cascading effects. Hopefully, we will not be adding many more contents. But there is bound to be some.

**Comment by janbjorge** [comment]
> > > That was a lot of added lines 🤯
> > > ```
> > > * [ ]  Also add `facies_thickness` to legacy schema, as we need it to have effect asap
> > > ```
> > 
> > 
> > Yeah, at some point we need to look at how the schema is generated. Im sure their are options that identical objects reused insted of recreated.
> 
> In the legacy schema, adding `facies_thickness` would simply be adding one more entry to that one list. However, now each allowed content lives much further down in the hierarchy. So there are cascading effects. Hopefully, we will not be adding many more contents. But there is bound to be some.

I could combine them by using an Union, then loads of these to collapse to one. But i think this is more future proof, also it allows us to be more precises once we start to add documentation to the pydantic models.

**Pull request merged**
