### PR TITLE
CLN: Lazy import pyarrow

### PR DESCRIPTION
**Pull request by janbjorge**
Im not 100% sure if this is better, i just hate it when you have to track two variables. 

This might also be an option, but its a bit much for this case i thing. 

https://docs.python.org/3/library/importlib.html#implementing-lazy-imports

### CODE REVIEW

**Review by mferrera — APPROVED** [review]
Nice

**Review by jcrivenaes — COMMENTED** [review]
Or just having pyarrow as a primary requirement? Do you remember the reason fot this HAS_PYARROW construct, @perolavsvendsen ?

**Comment by perolavsvendsen** [comment]
> Or just having pyarrow as a primary requirement? Do you remember the reason fot this HAS_PYARROW construct, @perolavsvendsen ?

Legacy from when we had to support older Python versions?

**Comment by perolavsvendsen** [comment]
> > Or just having pyarrow as a primary requirement? Do you remember the reason fot this HAS_PYARROW construct, @perolavsvendsen ?
> 
> Legacy from when we had to support older Python versions?

Looked at the history but could not find any information on this. Part of larger refactoring, and details are lost I guess 🤷‍♂️ I will stick to the hypothesis that this is old Python version support and that we can move on from this now 👍

**Comment by mferrera** [comment]
When I looked at the commit history it seemed it was added when support for Python 3.6 was added. I also checked the RMS Python environment and it is present there, as well as being a dependency in this package, so I think this change is fine. Not sure if this is strictly a need but at least offers some improved import time.

**Comment by janbjorge** [comment]
> When I looked at the commit history it seemed it was added when support for Python 3.6 was added. I also checked the RMS Python environment and pyarrow is present there, as well as being a dependency in this package, so I think this change is fine.

NIce, thanks for checking.

**Pull request merged**
