### PR TITLE
Export subfolder

### PR DESCRIPTION
**Pull request by perolavsvendsen**
Attempting a solution for #60 - exporting to subfolder.
Code will allow it, but issue a warning.

Have not tested edge-cases etc yet, and I also want to test it live. But have a look at the suggested concepts for doing this.

### CODE REVIEW

**Comment by perolavsvendsen** [comment]
Partially solving #60 - perhaps.

**Comment by perolavsvendsen** [comment]
Something weird with the behavior of warnings from inside RMS.
```
warnings.warn(
                "Exporting to a subfolder is a deviation from the standard "
                "and could have consequences for later dependencies",
                UserWarning
            )
```
...gives this:
```
UserWarning: Exporting to a subfolder is a deviation from the standard and could have consequences for later dependencies
  collected/processed and subsequently both 'independent' and object dependent
```

**Comment by jcrivenaes** [comment]
> Something weird with the behavior of warnings from inside RMS.
> 
> ```
> warnings.warn(
>                 "Exporting to a subfolder is a deviation from the standard "
>                 "and could have consequences for later dependencies",
>                 UserWarning
>             )
> ```
> 
> ...gives this:
> 
> ```
> UserWarning: Exporting to a subfolder is a deviation from the standard and could have consequences for later dependencies
>   collected/processed and subsequently both 'independent' and object dependent
> ```

That was cryptical!

**Review by jcrivenaes — APPROVED** [review]
OK

**Pull request merged**
