### PR TITLE
Removing modification of root logger as it creates unforseen consequences

### LINKED ISSUE #176: Setting root logger in a library
Setting the root logger level in a library is considered bad practice, espesially not in a `__init__` file where if changes it for the entire running process.

This should be changed:
https://github.com/equinor/fmu-dataio/blob/a443c46b1014c2e31b11105b75610dd0fd82507b/src/fmu/dataio/__init__.py#L23

### PR DESCRIPTION
**Pull request by ManInFez**
Resolves #176

### CODE REVIEW

**Review by jcrivenaes — COMMENTED** [review]
Looks OK with me. @perolavsvendsen  any thoughts?

**Comment by perolavsvendsen** [comment]
I guess logging is included in all submodules as well, and as such will work. We will loose the formatting of it, as far as I can see. Perhaps not a problem?

**Review by jcrivenaes — APPROVED** [review]
LGTM

**Comment by oyvindeide** [comment]
> I guess logging is included in all submodules as well, and as such will work. We will loose the formatting of it, as far as I can see. Perhaps not a problem?

As a general rule a library should not change the root log level or the formatting because it is not in charge of executing the process, and the root logger being global it can have unintended side effects. 

In this case it was blocking the logging in `ert` because it is a plugin there and it filtered out all the log statements. If you are in change of excecution, for example through a `main` function in a console script, then setting root log levels and formatting is perfectly fine to do.

**Pull request merged**
