### PR TITLE
Switch to Erts newer plugin system

### PR DESCRIPTION
**Pull request by berland**
Avoids DeprecationWarnings.

### CODE REVIEW

**Review by tnatt — APPROVED** [review]
LGTM 🙂

**Comment by tnatt** [comment]
Hehe still a draft :) just ping when done!

**Comment by berland** [comment]
oh, it is done, was just missing a final in the commit, now in place.

Is the plugin system tested in CI?

**Comment by tnatt** [comment]
> oh, it is done, was just missing a final in the commit, now in place.
> 
> Is the plugin system tested in CI?

Yes we are testing it! You'll find it under "tests/test_integration" if you want to have a look

**Comment by tnatt** [comment]
btw we have this commit prefix system, would you add the prefix `MAINT:` to the commit ? Then I can merge it in after 👍

**Comment by berland** [comment]
Fixed.

**Pull request merged**
